-- Migration: seed_shop_product_lookup
-- Seed data for product lookup table (114 rows)

INSERT INTO public.shop_product_lookup (product_name_raw, brand, category, subcategory, display_name, collection, product_type, colourway, size, active) VALUES
-- ACTIPH
('ACTIPH Water', 'ACTIPH', 'Functional Drinks', NULL, 'ACTIPH Water', NULL, NULL, NULL, NULL, true),
-- Barebell Bars
('Barebell Bars - Banana Dream', 'Barebell', 'Bars & Snacks', NULL, 'Barebell Bar - Banana Dream', NULL, NULL, NULL, NULL, true),
('Barebell Bars - Caramel Choco', 'Barebell', 'Bars & Snacks', NULL, 'Barebell Bar - Caramel Choco', NULL, NULL, NULL, NULL, true),
('Barebell Bars - Coco Choco', 'Barebell', 'Bars & Snacks', NULL, 'Barebell Bar - Coco Choco', NULL, NULL, NULL, NULL, true),
('Barebell Bars - Hazelnut & Nougat', 'Barebell', 'Bars & Snacks', NULL, 'Barebell Bar - Hazelnut & Nougat', NULL, NULL, NULL, NULL, true),
('Barebell Bars - Marshmallow Rocky Road', 'Barebell', 'Bars & Snacks', NULL, 'Barebell Bar - Marshmallow Rocky Road', NULL, NULL, NULL, NULL, true),
('Barebell Bars - Peanut Butter', 'Barebell', 'Bars & Snacks', NULL, 'Barebell Bar - Peanut Butter', NULL, NULL, NULL, NULL, true),
('Barebell Bars - Peanut Caramel', 'Barebell', 'Bars & Snacks', NULL, 'Barebell Bar - Peanut Caramel', NULL, NULL, NULL, NULL, true),
('Barebell Bars - Raspberry & Cream', 'Barebell', 'Bars & Snacks', NULL, 'Barebell Bar - Raspberry & Cream', NULL, NULL, NULL, NULL, true),
('Barebell Bars - Salty White Chocolate & Peanut', 'Barebell', 'Bars & Snacks', NULL, 'Barebell Bar - Salty White Choc & Peanut', NULL, NULL, NULL, NULL, true),
-- Barebell Shakes
('Barebell Shake - Chocolate', 'Barebell', 'Shakes', NULL, 'Barebell Shake - Chocolate', NULL, NULL, NULL, NULL, true),
('Barebell Shake - Strawberry', 'Barebell', 'Shakes', NULL, 'Barebell Shake - Strawberry', NULL, NULL, NULL, NULL, true),
('Barebell Shake - Vanilla', 'Barebell', 'Shakes', NULL, 'Barebell Shake - Vanilla', NULL, NULL, NULL, NULL, true),
-- Boost
('Boost', 'Boost', 'Functional Drinks', NULL, 'Boost', NULL, NULL, NULL, NULL, true),
-- C4
('C4 Energy', 'C4', 'Functional Drinks', NULL, 'C4 Energy', NULL, NULL, NULL, NULL, true),
-- Cano Water
('Cano Water (330ml)', 'Cano Water', 'Functional Drinks', NULL, 'Cano Water', NULL, NULL, NULL, NULL, true),
-- HIRO Hydration
('HIRO HYDRATION ELECTROLYTES - Citrus Spring', 'HIRO Hydration', 'Functional Drinks', 'Electrolytes', 'HIRO Electrolytes - Citrus Spring', NULL, NULL, NULL, NULL, true),
('HIRO HYDRATION ELECTROLYTES - Ginger & Lemon', 'HIRO Hydration', 'Functional Drinks', 'Electrolytes', 'HIRO Electrolytes - Ginger & Lemon', NULL, NULL, NULL, NULL, true),
('HIRO HYDRATION ELECTROLYTES - Watermelon', 'HIRO Hydration', 'Functional Drinks', 'Electrolytes', 'HIRO Electrolytes - Watermelon', NULL, NULL, NULL, NULL, true),
-- Misfits
('Misfit Bar - Brownie Batter', 'Misfits', 'Bars & Snacks', NULL, 'Misfit Bar - Brownie Batter', NULL, NULL, NULL, NULL, true),
('Misfit Bar - Caramel Popcorn', 'Misfits', 'Bars & Snacks', NULL, 'Misfit Bar - Caramel Popcorn', NULL, NULL, NULL, NULL, true),
('Misfit Bar - Cookie Dough', 'Misfits', 'Bars & Snacks', NULL, 'Misfit Bar - Cookie Dough', NULL, NULL, NULL, NULL, true),
('Misfit Bar - Peanut Butter Fudge', 'Misfits', 'Bars & Snacks', NULL, 'Misfit Bar - Peanut Butter Fudge', NULL, NULL, NULL, NULL, true),
-- Nocco BCAA
('Nocco - BCAA''s - Apple', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Apple', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Berry Rhubarb', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Berry Rhubarb', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Blood Orange', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Blood Orange', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Caribbean', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Caribbean', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Caribbean (Caffeine Free)', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Caribbean (Caffeine Free)', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Grand Sour', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Grand Sour', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Juicy Melba', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Juicy Melba', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Limon Del Sol', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Limon Del Sol', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Mango', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Mango', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Melon Blast', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Melon Blast', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Ramonade', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Ramonade', NULL, NULL, NULL, NULL, true),
('Nocco - BCAA''s - Stellar Blend', 'Nocco', 'Functional Drinks', 'BCAA', 'Nocco BCAA - Stellar Blend', NULL, NULL, NULL, NULL, true),
-- Nocco Electrolytes
('Nocco - Electrolytes - Blood Orange', 'Nocco', 'Functional Drinks', 'Electrolytes', 'Nocco Electrolytes - Blood Orange', NULL, NULL, NULL, NULL, true),
('Nocco - Electrolytes - Lemon/Lime', 'Nocco', 'Functional Drinks', 'Electrolytes', 'Nocco Electrolytes - Lemon/Lime', NULL, NULL, NULL, NULL, true),
-- ONE LDN Coffee
('Americano', 'ONE LDN', 'Coffee', NULL, 'Americano', NULL, NULL, NULL, NULL, true),
('Cappuccino - Large', 'ONE LDN', 'Coffee', NULL, 'Cappuccino - Large', NULL, NULL, NULL, NULL, true),
('Cappuccino - Small', 'ONE LDN', 'Coffee', NULL, 'Cappuccino - Small', NULL, NULL, NULL, NULL, true),
('Cortado', 'ONE LDN', 'Coffee', NULL, 'Cortado', NULL, NULL, NULL, NULL, true),
('Dirty Chai - Small', 'ONE LDN', 'Coffee', NULL, 'Dirty Chai', NULL, NULL, NULL, NULL, true),
('Espresso', 'ONE LDN', 'Coffee', NULL, 'Espresso', NULL, NULL, NULL, NULL, true),
('Flat White', 'ONE LDN', 'Coffee', NULL, 'Flat White', NULL, NULL, NULL, NULL, true),
('Hot Chocolate - Large', 'ONE LDN', 'Coffee', NULL, 'Hot Chocolate', NULL, NULL, NULL, NULL, true),
('Latte - Large', 'ONE LDN', 'Coffee', NULL, 'Latte - Large', NULL, NULL, NULL, NULL, true),
('Latte - Small', 'ONE LDN', 'Coffee', NULL, 'Latte - Small', NULL, NULL, NULL, NULL, true),
('Macchiato', 'ONE LDN', 'Coffee', NULL, 'Macchiato', NULL, NULL, NULL, NULL, true),
('Mocha - Small', 'ONE LDN', 'Coffee', NULL, 'Mocha', NULL, NULL, NULL, NULL, true),
('Tea', 'ONE LDN', 'Coffee', NULL, 'Tea', NULL, NULL, NULL, NULL, true),
-- ONE LDN Merch
('CREW SOCK - uk5-uk10', 'ONE LDN', 'Merch', NULL, 'Crew Sock', NULL, 'Sock', NULL, 'uk5-uk10', false),
('ONE LDN Athlete Hoodie - White/L', 'ONE LDN', 'Merch', NULL, 'Athlete Hoodie', 'Athlete', 'Hoodie', 'White', 'L', true),
('ONE LDN Athlete Hoodie - White/XL', 'ONE LDN', 'Merch', NULL, 'Athlete Hoodie', 'Athlete', 'Hoodie', 'White', 'XL', true),
('ONE LDN Athlete Hoodie - Yellow/M', 'ONE LDN', 'Merch', NULL, 'Athlete Hoodie', 'Athlete', 'Hoodie', 'Yellow', 'M', true),
('ONE LDN Athlete Tee - White/L', 'ONE LDN', 'Merch', NULL, 'Athlete Tee', 'Athlete', 'Tee', 'White', 'L', true),
('ONE LDN Athlete Tee - White/M', 'ONE LDN', 'Merch', NULL, 'Athlete Tee', 'Athlete', 'Tee', 'White', 'M', true),
('ONE LDN Training Dept. Tee - Black - Black/2XL', 'ONE LDN', 'Merch', NULL, 'Training Dept. Tee', 'Classic', 'Tee', 'Black', '2XL', true),
('ONE LDN Training Dept. Tee - Black - Black/L', 'ONE LDN', 'Merch', NULL, 'Training Dept. Tee', 'Classic', 'Tee', 'Black', 'L', true),
('ONE LDN Training Dept. Tee - Black - Black/M', 'ONE LDN', 'Merch', NULL, 'Training Dept. Tee', 'Classic', 'Tee', 'Black', 'M', true),
('ONE LDN Training Dept. Tee - Black - Black/XL', 'ONE LDN', 'Merch', NULL, 'Training Dept. Tee', 'Classic', 'Tee', 'Black', 'XL', true),
('ONE LDN Training Dept. Tee - Stone - Stone/2XL', 'ONE LDN', 'Merch', NULL, 'Training Dept. Tee', 'Classic', 'Tee', 'Stone', '2XL', true),
('ONE LDN Training Dept. Tee - Stone - Stone/L', 'ONE LDN', 'Merch', NULL, 'Training Dept. Tee', 'Classic', 'Tee', 'Stone', 'L', true),
('ONE LDN Training Dept. Tee - Stone - Stone/M', 'ONE LDN', 'Merch', NULL, 'Training Dept. Tee', 'Classic', 'Tee', 'Stone', 'M', true),
('ONE LDN Training Dept. Tee - Stone - Stone/XL', 'ONE LDN', 'Merch', NULL, 'Training Dept. Tee', 'Classic', 'Tee', 'Stone', 'XL', true),
('ONE LDN Unbeatable Contrast Tee - Black/2XL', 'ONE LDN', 'Merch', NULL, 'Unbeatable Contrast Tee', 'Essential', 'Contrast Tee', 'Black', '2XL', true),
('ONE LDN Unbeatable Contrast Tee - Black/L', 'ONE LDN', 'Merch', NULL, 'Unbeatable Contrast Tee', 'Essential', 'Contrast Tee', 'Black', 'L', true),
('ONE LDN Unbeatable Contrast Tee - Black/XL', 'ONE LDN', 'Merch', NULL, 'Unbeatable Contrast Tee', 'Essential', 'Contrast Tee', 'Black', 'XL', true),
('ONE LDN Washed Tank - Black/L', 'ONE LDN', 'Merch', NULL, 'Washed Tank', 'Essential', 'Tank', 'Black', 'L', true),
('ONE LDN Washed Tank - Black/M', 'ONE LDN', 'Merch', NULL, 'Washed Tank', 'Essential', 'Tank', 'Black', 'M', true),
('ONE LDN Washed Tank - Black/S', 'ONE LDN', 'Merch', NULL, 'Washed Tank', 'Essential', 'Tank', 'Black', 'S', true),
-- ONE LDN Services
('Fob', 'ONE LDN', 'Services', NULL, 'Fob', NULL, NULL, NULL, NULL, true),
('Shower Towel', 'ONE LDN', 'Services', NULL, 'Shower Towel', NULL, NULL, NULL, NULL, true),
-- ONE LDN Shakes
('Brunch', 'ONE LDN', 'Shakes', NULL, 'Brunch', NULL, NULL, NULL, NULL, true),
('Choco-Berry Cheesecake', 'ONE LDN', 'Shakes', NULL, 'Choco-Berry Cheesecake', NULL, NULL, NULL, NULL, true),
('Cinnamon Swirl', 'ONE LDN', 'Shakes', NULL, 'Cinnamon Swirl', NULL, NULL, NULL, NULL, true),
('PB&J', 'ONE LDN', 'Shakes', NULL, 'PB&J', NULL, NULL, NULL, NULL, true),
('Power (Lean)', 'ONE LDN', 'Shakes', NULL, 'Power (Lean)', NULL, NULL, NULL, NULL, true),
('Protein Powder - Vegan', 'ONE LDN', 'Shakes', NULL, 'Protein Powder - Vegan', NULL, NULL, NULL, NULL, true),
('Protein Powder - Whey', 'ONE LDN', 'Shakes', NULL, 'Protein Powder - Whey', NULL, NULL, NULL, NULL, true),
('Shake Extras - Banana', 'ONE LDN', 'Shakes', 'Extras', 'Shake Extras - Banana', NULL, NULL, NULL, NULL, true),
('Shake Extras - Berries', 'ONE LDN', 'Shakes', 'Extras', 'Shake Extras - Berries', NULL, NULL, NULL, NULL, true),
('Shake Extras - Creatine', 'ONE LDN', 'Shakes', 'Extras', 'Shake Extras - Creatine', NULL, NULL, NULL, NULL, true),
('Shake Extras - Nut Butter', 'ONE LDN', 'Shakes', 'Extras', 'Shake Extras - Nut Butter', NULL, NULL, NULL, NULL, true),
('Shake Extras - Oats', 'ONE LDN', 'Shakes', 'Extras', 'Shake Extras - Oats', NULL, NULL, NULL, NULL, true),
('Staff Shake', 'ONE LDN', 'Shakes', NULL, 'Staff Shake', NULL, NULL, NULL, NULL, true),
('THE ONE PB', 'ONE LDN', 'Shakes', NULL, 'The One PB', NULL, NULL, NULL, NULL, true),
-- Red Bull
('Redbull - Editions - Blue Edition', 'Red Bull', 'Functional Drinks', 'Editions', 'Red Bull - Blue Edition', NULL, NULL, NULL, NULL, true),
('Redbull - Editions - Coconut Edition', 'Red Bull', 'Functional Drinks', 'Editions', 'Red Bull - Coconut Edition', NULL, NULL, NULL, NULL, true),
('Redbull - Editions - Ice Edition', 'Red Bull', 'Functional Drinks', 'Editions', 'Red Bull - Ice Edition', NULL, NULL, NULL, NULL, true),
('Redbull - Editions - Pink Edition', 'Red Bull', 'Functional Drinks', 'Editions', 'Red Bull - Pink Edition', NULL, NULL, NULL, NULL, true),
('Redbull - Editions - Summer Edition', 'Red Bull', 'Functional Drinks', 'Editions', 'Red Bull - Summer Edition', NULL, NULL, NULL, NULL, true),
('Redbull - Originals - Original', 'Red Bull', 'Functional Drinks', 'Original', 'Red Bull - Original', NULL, NULL, NULL, NULL, true),
('Redbull - Originals - Sugar Free', 'Red Bull', 'Functional Drinks', 'Original', 'Red Bull - Sugar Free', NULL, NULL, NULL, NULL, true),
-- Tenzing
('Tenzing   - Apple & Seaberry', 'Tenzing', 'Functional Drinks', NULL, 'Tenzing - Apple & Seaberry', NULL, NULL, NULL, NULL, true),
('Tenzing   - Fiery Mango', 'Tenzing', 'Functional Drinks', NULL, 'Tenzing - Fiery Mango', NULL, NULL, NULL, NULL, true),
('Tenzing   - Lime & Mint', 'Tenzing', 'Functional Drinks', NULL, 'Tenzing - Lime & Mint', NULL, NULL, NULL, NULL, true),
('Tenzing   - Original', 'Tenzing', 'Functional Drinks', NULL, 'Tenzing - Original', NULL, NULL, NULL, NULL, true),
('Tenzing   - Peach & Honey Melon', 'Tenzing', 'Functional Drinks', NULL, 'Tenzing - Peach & Honey Melon', NULL, NULL, NULL, NULL, true),
('Tenzing   - Pineapple & Passionfruit', 'Tenzing', 'Functional Drinks', NULL, 'Tenzing - Pineapple & Passionfruit', NULL, NULL, NULL, NULL, true),
('Tenzing   - Raspberry & Yuzu', 'Tenzing', 'Functional Drinks', NULL, 'Tenzing - Raspberry & Yuzu', NULL, NULL, NULL, NULL, true),
-- UFit
('UFit - Chocolate', 'UFit', 'Shakes', NULL, 'UFit - Chocolate', NULL, NULL, NULL, NULL, true),
('UFit - Salted Caramel', 'UFit', 'Shakes', NULL, 'UFit - Salted Caramel', NULL, NULL, NULL, NULL, true),
('UFit - Strawberry', 'UFit', 'Shakes', NULL, 'UFit - Strawberry', NULL, NULL, NULL, NULL, true),
('UFit - Vanilla', 'UFit', 'Shakes', NULL, 'UFit - Vanilla', NULL, NULL, NULL, NULL, true),
('UFit - White Chocolate', 'UFit', 'Shakes', NULL, 'UFit - White Chocolate', NULL, NULL, NULL, NULL, true),
-- Vitamin Well
('Vitamin Well - 001 Isotonic', 'Vitamin Well', 'Functional Drinks', NULL, 'Vitamin Well - 001 Isotonic', NULL, NULL, NULL, NULL, true),
('Vitamin Well - 002 Sugar Free', 'Vitamin Well', 'Functional Drinks', NULL, 'Vitamin Well - 002 Sugar Free', NULL, NULL, NULL, NULL, true),
('Vitamin Well - Elevate', 'Vitamin Well', 'Functional Drinks', NULL, 'Vitamin Well - Elevate', NULL, NULL, NULL, NULL, true),
('Vitamin Well - Enhance', 'Vitamin Well', 'Functional Drinks', NULL, 'Vitamin Well - Enhance', NULL, NULL, NULL, NULL, true),
('Vitamin Well - Hydrate', 'Vitamin Well', 'Functional Drinks', NULL, 'Vitamin Well - Hydrate', NULL, NULL, NULL, NULL, true),
('Vitamin Well - Peach', 'Vitamin Well', 'Functional Drinks', NULL, 'Vitamin Well - Peach', NULL, NULL, NULL, NULL, true),
('Vitamin Well - Raspberry', 'Vitamin Well', 'Functional Drinks', NULL, 'Vitamin Well - Raspberry', NULL, NULL, NULL, NULL, true),
('Vitamin Well - Recover', 'Vitamin Well', 'Functional Drinks', NULL, 'Vitamin Well - Recover', NULL, NULL, NULL, NULL, true),
('Vitamin Well - Reload', 'Vitamin Well', 'Functional Drinks', NULL, 'Vitamin Well - Reload', NULL, NULL, NULL, NULL, true)
ON CONFLICT (product_name_raw) DO NOTHING;
